import React, { useState } from "react";

import { AiOutlineEdit } from "react-icons/ai";
import { Link } from "react-router-dom";
import { IoArrowBack } from "react-icons/io5";
import { HiOutlineArchiveBox } from "react-icons/hi2";
import {
  FiTrash,
  FiSend,
  FiPlus,
  FiExternalLink,
  FiUpload,
} from "react-icons/fi";
import { AiOutlineEye } from "react-icons/ai";
import { FiPhone, FiMail, FiMessageSquare } from "react-icons/fi";

const JobCardNext = () => {
  const [activeTab, setActiveTab] = useState("Overview");
  const [activeTabBtn, setActiveTabBtn] = useState("Asset");

  const tabs = ["Overview", "Checklists", "Job Card Log"];
  return (
    <div className="min-h-screen  mt-24 bg-white p-6">
      <div className="bg-white ">
        <div className="flex justify-between items-center px-6 py-4">
          <div className="flex items-start gap-3">
            <IoArrowBack className="text-2xl text-gray-700 cursor-pointer mt-1 border-2 rounded-[50%]" />
            <div>
              <h1 className="text-xl font-bold">Job Card #30000</h1>
              <div className="text-xs text-gray-600 mt-1">
                <span className="font-semibold">Created:</span> May 02, 2025 :
                06:06pm &nbsp;&nbsp;
                <span className="font-semibold">Generated by:</span> Clark Kelly
                &nbsp;&nbsp;
                <span className="font-semibold">Claimed by:</span>{" "}
                <span className="text-blue-500 cursor-pointer">Edit</span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <span className="text-sm text-blue-500 cursor-pointer">
              Recurring Job
            </span>
            <button className="flex items-center gap-1 border px-3 py-1 rounded text-sm hover:bg-gray-100">
              <HiOutlineArchiveBox className="text-md" />
              Archive
            </button>
          </div>
        </div>

        <div className="flex px-6 border-b border-gray-200 mb-4 text-sm font-medium text-gray-700">
          {tabs.map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 -mb-px transition ${
                activeTab === tab
                  ? "text-blue-600 border-b-2 border-blue-600"
                  : "hover:text-blue-500"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>
      </div>
      <div className="flex justify-between items-start gap-6">
        <div className="w-3/4 bg-white space-y-6">
          <div className="border border-gray-300 rounded-xl p-4 space-y-4 shadow-sm">
            <div className="p-6 max-w-4xl mx-auto text-sm text-gray-800">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <h2 className="text-xl font-bold">Sterling Infotech</h2>
                  <p>Client Site - 345-9610 Aliquam Rd</p>
                  <p>Abhishek Jain</p>
                  <p>1232444444</p>
                  <p>user1@sterlinginfotech.com</p>
                  <Link
                    to="#"
                    className="text-blue-500 text-[10px] border-b mt-1 inline-block"
                  >
                    Edit Contact
                  </Link>
                </div>

                <Link
                  to="#"
                  className="text-blue-500 text-[15px] border-b mt-1 inline-block"
                >
                  Edit Contact
                </Link>
              </div>

              <hr className="mb-4 text-gray-200" />

              <div className="flex justify-between items-center mb-4">
                <span className="text-gray-600">Sites</span>
                <span className="font-medium text-sm">Client Site</span>
              </div>

              <hr className="mb-4 text-gray-200" />

              <div className="mb-4">
                <p className="text-gray-600 mb-2">Warranty</p>
                <div className="flex gap-2">
                  <button className="bg-gray-100 text-xs px-3 py-1 rounded">
                    WARRANTY
                  </button>
                  <button className="bg-gray-100 text-xs px-3 py-1 rounded">
                    OUT OF WARRANTY
                  </button>
                  <button className="bg-gray-100 text-xs px-3 py-1 rounded">
                    FOC
                  </button>
                </div>
              </div>

              <div className="mb-6">
                <p className="font-semibold text-sm mb-2">Job Type</p>
                <div className="border border-gray-200 rounded-md px-4 py-3 flex justify-between items-center w-[100%] max-w-md">
                  <select name="" id="" className="w-[720px] ">
                    <option value="">Installation</option>
                    <option value="">Select</option>
                    <option value="">Installation Guide</option>
                  </select>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <p className="font-semibold text-sm mb-3">Asset(s)</p>
                </div>
                <button className="flex items-center gap-1 border px-4 py-2 text-sm rounded hover:bg-gray-100">
                  <span className="text-lg">+</span> Add Asset
                </button>
              </div>
            </div>

            <div className="p-6 max-w-5xl mx-auto space-y-8">
              {/* Card */}
              <div className="bg-blue-50 p-4 rounded-lg shadow-sm flex justify-between items-start w-60">
                <div>
                  <h4 className="font-semibold text-gray-800">test</h4>
                  <a
                    href="#"
                    className="text-sky-600 text-sm underline block mt-1"
                  >
                    Checklist 0/1
                  </a>
                  <div className="mt-4 w-12 h-12 flex items-center justify-center rounded-full border-4 border-blue-200 text-xs font-bold text-sky-600">
                    0%
                  </div>
                </div>
                <button className="text-gray-500 hover:text-red-500">
                  <FiTrash />
                </button>
              </div>

              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-gray-800 text-base">
                    Technicians
                  </h3>
                </div>
                <div className="flex items-center gap-3">
                  <button className="flex items-center gap-2 border px-4 py-2 rounded-md text-sm text-gray-700 hover:bg-gray-100">
                    <FiExternalLink />
                    Send Job Card
                  </button>
                  <button className="flex items-center gap-2 border px-4 py-2 rounded-md text-sm text-gray-700 hover:bg-gray-100">
                    <FiPlus />
                    Add Technician
                  </button>
                </div>
              </div>
              <div>
                <p className="text-sm text-gray-600">
                  Click{" "}
                  <a href="#" className="text-sky-600 underline">
                    here
                  </a>{" "}
                  to add a technician
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-gray-800 text-base">
                  Technician Notes
                </h3>
                <p className="text-sm text-gray-400">
                  Technician notes are shown in the Job Card email and Job Card
                  URL which is seen by Technicians.
                </p>
                <p className="text-sm text-gray-600 mt-1">
                  Click{" "}
                  <a href="#" className="text-sky-600 underline">
                    here
                  </a>{" "}
                  to add a Technician Notes.
                </p>
              </div>

              <div>
                <h3 className="font-semibold text-gray-800 text-base">
                  Attachments
                </h3>
                <div className="flex justify-end">
                  <button className="text-gray-500 hover:text-sky-500">
                    <FiUpload />
                  </button>
                </div>
              </div>
                <hr className="mb-4 text-gray-200" />

              <div className="pb-6">
                <h3 className="font-semibold text-gray-800 text-base">
                  Checklist Uploads
                </h3>
              </div>
            </div>
          </div>

          <div className="border border-gray-200 p-6 rounded-lg shadow-sm bg-white max-w-4xl mx-auto mt-6">
            <h2 className="text-base font-semibold text-gray-800 mb-3">
              Comments / Updates
            </h2>

            <textarea
              placeholder="Start typing..."
              className="w-full h-28 border border-gray-300 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-sky-300 mb-4 resize-none"
            />

            <div>
              <p className="text-sm text-gray-600 mb-2">Save As:</p>
              <div className="flex gap-3">
                <button className="border p-3 rounded-md text-gray-700 hover:bg-gray-100">
                  <FiPhone size={18} />
                </button>
                <button className="border p-3 rounded-md text-gray-700 hover:bg-gray-100">
                  <FiMail size={18} />
                </button>
                <button className="border p-3 rounded-md text-gray-700 hover:bg-gray-100">
                  <FiMessageSquare size={18} />
                </button>
              </div>
            </div>
          </div>
          <div className="border border-gray-200 p-6 rounded-lg shadow-sm bg-white max-w-4xl mx-auto">
            <h2 className="text-lg font-semibold text-gray-800 mb-4">
              Ticket History
            </h2>

            <div className="flex space-x-6 border-b border-gray-200 mb-4 text-sm font-medium">
              <button
                onClick={() => setActiveTabBtn("Asset")}
                className={`pb-1 ${
                  activeTabBtn === "Asset"
                    ? "text-sky-600 border-b-2  border-sky-500"
                    : "text-gray-500"
                }`}
              >
                Asset
              </button>
              <button
                onClick={() => setActiveTabBtn("Site")}
                className={`pb-1 ${
                  activeTabBtn === "Site"
                    ? "text-sky-600 border-b-2 border-sky-500"
                    : "text-gray-500"
                }`}
              >
                Site
              </button>
            </div>

            <div className="overflow-x-auto">
              <table className="min-w-full text-sm text-left border border-gray-200">
                <thead className="bg-sky-100 text-gray-800 font-semibold">
                  <tr>
                    <th className="py-2 px-4">Ticket Title</th>
                    <th className="py-2 px-4">Date</th>
                    <th className="py-2 px-4">Ticket Owner</th>
                    <th className="py-2 px-4">Status</th>
                    <th className="py-2 px-4"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-t border-gray-300">
                    <td className="py-3 px-4">#</td>
                    <td className="py-3 px-4">May 02, 2025</td>
                    <td className="py-3 px-4"></td>
                    <td className="py-3 px-4"></td>
                    <td className="py-3 px-4">
                      <button className="border p-1 rounded hover:bg-gray-100">
                        <AiOutlineEye size={18} />
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div className="w-1/4 bg-[#1f2b33] text-white p-4 rounded shadow-sm">
          <div className="flex justify-between items-center mb-4">
            <h4 className="font-bold text-sm">Job Status</h4>
            <AiOutlineEdit />
          </div>
          <p className="text-sm mb-4">Friday May 02, 2025</p>

          <ul className="space-y-2 text-xs">
            <li className="bg-yellow-500 p-2 rounded">Job Scheduled</li>
            <li className="bg-yellow-500 p-2 rounded">Client Confirmed</li>
            <li className="bg-green-600 p-2 rounded">Technician Assigned</li>
            <li className="bg-gray-700 p-2 rounded">Technician Enroute</li>
            <li className="bg-gray-700 p-2 rounded">Client Call Confirmed</li>
            <li className="bg-gray-700 p-2 rounded">Job Card Sent</li>
            <li className="bg-gray-700 p-2 rounded">Checklist Complete</li>
            <li className="bg-gray-700 p-2 rounded">Material Review</li>
            <li className="bg-gray-700 p-2 rounded">Job Finished</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default JobCardNext;
